name: FOSDEM

options:
  tabWidth: 2
  indentWidth: 2
  knownRegions: ["en", "Base"]
  createIntermediateGroups: true
  bundleIdPrefix: com.mttcrsp.fosdem

settings:
  SWIFT_TREAT_WARNINGS_AS_ERRORS: 'YES'

packages:
  GRDB:
    url: https://github.com/mttcrsp/GRDB.swift
    branch: master

targets:
  FOSDEM:
    type: application
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - Sources
    - Resources
    scheme:
      environmentVariables:
        ENABLE_SCHEDULE_UPDATES: "1"
        ENABLE_ONBOARDING: "1"
      gatherCoverageData: true
      testTargets:
        - name: UITests
          randomExecutionOrder: true
    dependencies:
    - target: Core_iOS
    prebuildScripts:
    - script: swiftgen
    postbuildScripts:
    - script: swiftformat .
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        DEVELOPMENT_TEAM: 3CM92FF2C5
        INFOPLIST_FILE: Resources/Info.plist
        MARKETING_VERSION: 1.2.0
        PRODUCT_BUNDLE_IDENTIFIER: com.mttcrsp.fosdem
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_MODULE_NAME: Fosdem
        TARGETED_DEVICE_FAMILY: "1,2"
        VERSIONING_SYSTEM: apple-generic

  Core:
    type: framework
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: 11.0
      tvOS: 10.15
    sources:
    - Core/Sources
    dependencies:
    - package: GRDB
    testTargets:
      - name: Tests
        randomExecutionOrder: true

  CoreTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: '10.15'
    sources:
    - Core/Tests
    - Resources/Buildings
    dependencies:
    - target: Core_macOS
    postbuildScripts:
    - script: swiftformat .

  UITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - UITests
    - Core/Tests/BundleDataLoader.swift
    dependencies:
    - target: FOSDEM
    postbuildScripts:
    - script: swiftformat .
    settings:
      base:
        INFOPLIST_FILE: UITests/Resources/Info.plist

  GenerateDB:
    type: tool
    platform: macOS
    deploymentTarget: '10.15'
    sources:
    - Scripts/GenerateDB.swift
    dependencies:
    - target: Core_macOS
    postbuildScripts:
    - script: swiftformat .
