name: FOSDEM

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    exactVersion: 6.29.3
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    exactVersion: 1.17.6

options:
  bundleIdPrefix: com.mttcrsp.fosdem
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "14.0"
    macOS: '10.13'
  transitivelyLinkDependencies: true
  preGenCommand: make run_mockolo run_swiftgen

settings:
  DEVELOPMENT_TEAM: "3CM92FF2C5"

targets:
  FOSDEM:
    type: application
    platform: iOS
    sources:
      - App/Sources
      - App/Resources
    dependencies:
      - package: GRDB
    settings:
      CODE_SIGN_ENTITLEMENTS: App/Resources/FOSDEM.entitlements
      CURRENT_PROJECT_VERSION: 2
      INFOPLIST_FILE: App/Resources/Info.plist
      MARKETING_VERSION: 1.6.0
      PRODUCT_BUNDLE_IDENTIFIER: com.mttcrsp.fosdem
      PRODUCT_MODULE_NAME: Fosdem
    scheme:
      environmentVariables:
        ENABLE_ONBOARDING: "1"
        ENABLE_SCHEDULE_UPDATES: "1"
      gatherCoverageData: true
      testTargets:
        - name: Tests
          randomExecutionOrder: true
        - name: SnapshotTests
          randomExecutionOrder: true
        - name: UITests
          randomExecutionOrder: true

  Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - App/Tests
      - App/Mocks
      - App/Resources/Buildings
    dependencies:
      - target: FOSDEM
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FOSDEM.app/FOSDEM"

  SnapshotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: App/SnapshotTests
        excludes:
          - __Snapshots__
      - App/Mocks
    dependencies:
      - target: FOSDEM
      - package: SnapshotTesting
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FOSDEM.app/FOSDEM"

  UITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
    - App/UITests
    - App/Tests/BundleDataLoader.swift
    dependencies:
    - target: FOSDEM
    settings:
      GENERATE_INFOPLIST_FILE: YES
