name: FOSDEM

packages:
  GRDB:
    url: https://github.com/mttcrsp/GRDB.swift
    branch: master
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    exactVersion: 1.8.2

options:
  bundleIdPrefix: com.mttcrsp.fosdem
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "11.0"
    macOS: '10.13'
  transitivelyLinkDependencies: true
  preGenCommand: make run_mockolo run_swiftgen

settings:
  DEVELOPMENT_TEAM: "3CM92FF2C5"

targetTemplates:
  Formattable:
    preBuildScripts:
      - script: make run_swiftformat
        name: SwiftFormat
        basedOnDependencyAnalysis: false

targets:
  FOSDEM:
    type: application
    platform: iOS
    sources:
      - App/Sources
      - App/Resources
    dependencies:
      - package: GRDB
      - target: CoreUI
    settings:
      CODE_SIGN_ENTITLEMENTS: App/Resources/FOSDEM.entitlements
      CURRENT_PROJECT_VERSION: 2
      INFOPLIST_FILE: App/Resources/Info.plist
      MARKETING_VERSION: 1.4.0
      PRODUCT_BUNDLE_IDENTIFIER: com.mttcrsp.fosdem
      PRODUCT_MODULE_NAME: Fosdem
    scheme:
      environmentVariables:
        ENABLE_ONBOARDING: "1"
        ENABLE_SCHEDULE_UPDATES: "1"
      gatherCoverageData: true
      testTargets:
        - name: Tests
          randomExecutionOrder: true
        - name: SnapshotTests
          randomExecutionOrder: true
        - name: UITests
          randomExecutionOrder: true
    templates:
      - Formattable

  Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - App/Tests
      - App/Mocks
      - App/Resources/Buildings
    dependencies:
      - target: FOSDEM
    preBuildScripts:
      - script: make run_swiftformat
        name: SwiftFormat
        basedOnDependencyAnalysis: false
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FOSDEM.app/FOSDEM"

  SnapshotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: App/SnapshotTests
        excludes:
          - __Snapshots__
      - App/Mocks
    dependencies:
      - target: FOSDEM
      - package: SnapshotTesting
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FOSDEM.app/FOSDEM"
    templates:
      - Formattable

  UITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
    - App/UITests
    - App/Tests/BundleDataLoader.swift
    dependencies:
    - target: FOSDEM
    settings:
      GENERATE_INFOPLIST_FILE: YES
    templates:
      - Formattable
  
  CoreUI:
    type: framework
    platform: iOS
    sources:
    - Modules/CoreUI/Sources
    settings:
      GENERATE_INFOPLIST_FILE: YES
    templates:
      - Formattable

  GenerateDB:
    type: tool
    platform: macOS
    sources:
    - App/Sources/Derived/Strings.swift
    - App/Sources/Models/Conference.swift
    - App/Sources/Models/Room.swift
    - App/Sources/Models/Day.swift
    - App/Sources/Models/Attachment.swift
    - App/Sources/Models/Link.swift
    - App/Sources/Models/ScheduleXMLParser.swift
    - App/Sources/Models/Event.swift
    - App/Sources/Models/Track.swift
    - App/Sources/Models/Person.swift
    - App/Sources/Models/Participation.swift
    - App/Sources/Models/Schedule.swift
    - App/Sources/Models/Queries/ImportSchedule.swift
    - App/Sources/Models/Requests/ScheduleRequest.swift
    - App/Sources/Models/Tables
    - App/Sources/Models/Migrations
    - App/Sources/Services/PersistenceService.swift
    - App/Sources/Services/NetworkService.swift
    - App/Sources/Extensions/DateComponentsFormatter+Extensions.swift
    - App/Sources/Extensions/DateFormatter+Extensions.swift
    - Scripts/GenerateDB.swift
    dependencies:
      - package: GRDB
    templates:
      - Formattable