name: FOSDEM

options:
  tabWidth: 2
  indentWidth: 2
  knownRegions: ["en", "Base"]
  createIntermediateGroups: true
  bundleIdPrefix: com.mttcrsp.fosdem

settings:
  SWIFT_TREAT_WARNINGS_AS_ERRORS: 'YES'
  SWIFT_VERSION: '5.1'

packages:
  GRDB:
    url: https://github.com/mttcrsp/GRDB.swift
    branch: master
  CrashReporter:
    url: https://github.com/microsoft/plcrashreporter
    branch: master

targets:
  FOSDEM:
    type: application
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - Sources
    - Resources
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: Tests
          randomExecutionOrder: true
        - name: UITests
          randomExecutionOrder: true
    dependencies:
    - package: GRDB
    - package: CrashReporter
    postbuildScripts:
    - script: swiftformat .
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        DEVELOPMENT_TEAM: 3CM92FF2C5
        INFOPLIST_FILE: Resources/Info.plist
        MARKETING_VERSION: 1.0.0
        PRODUCT_BUNDLE_IDENTIFIER: com.mttcrsp.fosdem
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_MODULE_NAME: Fosdem
        TARGETED_DEVICE_FAMILY: "1,2"
        VERSIONING_SYSTEM: apple-generic

  Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - Tests
    - Resources/Buildings
    dependencies:
    - target: FOSDEM
    postbuildScripts:
    - script: swiftformat .
    settings:
      INFOPLIST_FILE: Tests/Resources/Info.plist
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FOSDEM.app/FOSDEM"

  UITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - UITests
    dependencies:
    - target: FOSDEM
    postbuildScripts:
    - script: swiftformat .
    settings:
      base:
        INFOPLIST_FILE: UITests/Info.plist
