name: FOSDEM

options:
  tabWidth: 2
  indentWidth: 2
  knownRegions: ["en", "Base"]
  createIntermediateGroups: true
  bundleIdPrefix: com.mttcrsp.fosdem

settings:
  SWIFT_TREAT_WARNINGS_AS_ERRORS: 'YES'

packages:
  GRDB:
    url: https://github.com/mttcrsp/GRDB.swift
    branch: master

targets:
  FOSDEM:
    type: application
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - Sources
    - Resources
    scheme:
      environmentVariables:
        ENABLE_SCHEDULE_UPDATES: "1"
        ENABLE_ONBOARDING: "1"
      gatherCoverageData: true
      testTargets:
        - name: Tests
          randomExecutionOrder: true
        - name: UITests
          randomExecutionOrder: true
    dependencies:
    - package: GRDB
    prebuildScripts:
    - script: swiftgen
    postbuildScripts:
    - script: swiftformat .
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        DEVELOPMENT_TEAM: 3CM92FF2C5
        INFOPLIST_FILE: Resources/Info.plist
        MARKETING_VERSION: 1.2.0
        PRODUCT_BUNDLE_IDENTIFIER: com.mttcrsp.fosdem
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_MODULE_NAME: Fosdem
        TARGETED_DEVICE_FAMILY: "1,2"
        VERSIONING_SYSTEM: apple-generic

  Core:
    platform: macOS
    type: framework
    sources:
    - Core/Sources
    dependencies:
    - package: GRDB

  Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - Tests
    - Resources/Buildings
    dependencies:
    - target: FOSDEM
    postbuildScripts:
    - script: swiftformat .
    settings:
      INFOPLIST_FILE: Tests/Resources/Info.plist
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FOSDEM.app/FOSDEM"

  UITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: '11.0'
    sources:
    - UITests
    - Tests/BundleDataLoader.swift
    dependencies:
    - target: FOSDEM
    postbuildScripts:
    - script: swiftformat .
    settings:
      base:
        INFOPLIST_FILE: UITests/Resources/Info.plist

  GenerateDB:
    type: tool
    platform: macOS
    deploymentTarget: '10.13'
    sources:
    - Sources/Models/Conference.swift
    - Sources/Models/Room.swift
    - Sources/Models/Day.swift
    - Sources/Models/Attachment.swift
    - Sources/Models/Link.swift
    - Sources/Models/ScheduleXMLParser.swift
    - Sources/Models/Event.swift
    - Sources/Models/Track.swift
    - Sources/Models/Person.swift
    - Sources/Models/Participation.swift
    - Sources/Models/Schedule.swift
    - Sources/Models/Queries/ImportSchedule.swift
    - Sources/Models/Requests/ScheduleRequest.swift
    - Sources/Models/Tables
    - Sources/Models/Migrations
    - Sources/Services/PersistenceService.swift
    - Sources/Services/NetworkService.swift
    - Sources/Extensions/DateComponentsFormatter+Extensions.swift
    - Sources/Extensions/DateFormatter+Extensions.swift
    - Scripts/GenerateDB.swift
    dependencies:
    - package: GRDB
    postbuildScripts:
    - script: swiftformat .
